const textos = {
    en: {
        espanol: "Spanish",
        ingles: "English",
        saludo: "Greeter",
        nombre: "Enter Your Name:",
        genero: "Choose Your Gender",
        masculino: "Male",
        femenino: "Female",
        otro: "Other",
        edad: "Enter Your Age:",
        boton: "Greet",
        manana: "Good morning",
        tarde: "Good afternoon",
        noche: "Good evening",
        placerMasculinoJoven: "a pleasure to have you here young boy",
        placerMasculinoAdulto: "a pleasure to have you here Mr.",
        placerFemeninoJoven: "a pleasure to have you here younf lady",
        placerFemeninoAdulto: "a pleasure to have you here Mrs.",
        placerOtroJoven: "a pleasure to have you here young person",
        placerOtroAdulto: "a pleasure to have you here Sir/Madam",
    },
    es: {
        espanol: "Espanol",
        ingles: "Ingles",
        saludo: "Saludador",
        nombre: "Ingresa Tu Nombre:",
        genero: "Escoge Tu Genero",
        masculino: "Masculino",
        femenino: "Femenino",
        otro: "Otro",
        edad: "Ingresa Tu edad:",
        boton: "Saludar",
        manana: "Buenos días",
        tarde: "Buenas tardes",
        noche: "Buenas noches",
        placerMasculinoJoven: "un placer tenerte aquí joven caballero",
        placerMasculinoAdulto: "un placer tenerte aquí Sr.",
        placerFemeninoJoven: "un placer tenerte aquí joven dama",
        placerFemeninoAdulto: "un placer tenerte aquí Sra.",
        placerOtroJoven: "un placer tenerte aquí joven",
        placerOtroAdulto: "un placer tenerle aquí Estimado/Estimada",
    }
}

export default textos;